FROM pytorch/torchserve:latest

WORKDIR /home/model-server

COPY model-store ./model-store

COPY torchserve/config.properties ./config.properties

EXPOSE 8080 8081

CMD ["torchserve", \
     "--start", \
     "--model-store", "model-store", \
     "--models", "mymodel=mymodel.mar", \
     "--ts-config", "config.properties", \
     "--foreground"]