data_params:
  data_path: "Yegor25/lyrics_genre_dataset_small"
  test_size: 0.1
  seed: 0
save_params:
  save_path: "./bert_genre_model"
  save_hf: True
  hf_path: "Yegor25/bert_genre_model"
log_params:
  log_path: "./logs"
  log_steps: 100
train_params:
  model_name: "distilbert-base-multilingual-cased"
  max_length: 512
  batch_size: 8
  accum_size: 4
  epochs: 0.1
  learning_rate: 0.00005
  weight_decay: 0.01

